### ISSUE TITLE
[BUG] Generator showing empty slots in the recipe section

### ISSUE THREAD

**Issue by TheBusyBiscuit** [J3fftw1/LiteXpansion#114]
## Description (REQUIRED)

The "Generator" shows a lot of empty slots.
![f6dfd8010ebbd12ce9a95dd19d697fe4](https://user-images.githubusercontent.com/3967898/97875512-c831e380-1d1a-11eb-8cf2-3e3524597d32.png)

This is very likely the same issue that was adressed for the Coal Generator here:
https://github.com/Slimefun/Slimefun4/issues/2411

## Steps to reproduce the Issue (REQUIRED)

1. Open up the Slimefun Guide
2. Navigate to the Generator
3. Look at the Recipes

## Expected behavior (REQUIRED)

There should not be any empty slots.

## Server Log

*Nothing out of the ordinary*

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper 
 - Minecraft version: 1.16.3
 - CS-CoreLib version: DEV - 87
 - Slimefun version: DEV  736
 - LiteXpansion version: DEV - 94

**Comment by J3fftw1** [comment]
No need for an issue when you fix it instantly
Thanks anyways
