### ISSUE TITLE
Ore Crusher doesn't make Coal into Coal Dust

### ISSUE THREAD

**Issue by por26** [J3fftw1/LiteXpansion#116]
## Description (REQUIRED)
Coal Dust can't be made using Ore Crusher

## Steps to reproduce the Issue (REQUIRED)
Place Coal in the dispenser and it will send you "Sorry, I could not recognize..." after you activated it

## Expected behavior (REQUIRED)
It should make the coal dust instantly after placing and activating the basic machine.

## Server Log
No errors on server's logs

## Environment (REQUIRED)
Server Software (Spigot/Paper): paper-1.16.4
Minecraft Version: 1.16.4
Slimefun Version: DEV - 744
CS-CoreLib Version: DEV - 79:

**Comment by Kritum** [comment]
please, it is solved?

**Comment by J3fftw1** [comment]
Yes why would i else close it

**Comment by Kritum** [comment]
tks
