### ISSUE TITLE
[BUG] LiteXpansion erroring out upon loading UU-Matter recipes

### ISSUE THREAD

**Issue by SpeedRunHunter** [J3fftw1/LiteXpansion#125]
## Description
When I startup the server LiteXpansion gets to "Loaded 35 UU-Matter recipes", and then errors out with a NoSuchMethodError. Specificly dev.j3fftw.litexpansion.uumatter.UuMatterCategory.register(); corrupted version file, or just dum thing on my part? Maybe this error can be ignored?

## Steps to reproduce the Issue
I just startup the server. There's a metric button of other SF addons - I just download all of them and try using them at once - that load before LiteXP, as well as some other plugins, like Multiverse, Essentials, and some other utility plugins.

## Expected behavior
For LiteXP to load; doj.

## Server Log
Log: https://pastebin.com/r72gVy6p

## Environment
 - Server Software (Spigot/Paper): git-Paper-253
 - Minecraft version: 1.16.3
 - CS-CoreLib version: vDEV - 92
 - Slimefun version: vDEV - 783
 - LiteXpansion version: vDEV - 118

![image](https://user-images.githubusercontent.com/30046335/104575617-847f2280-5657-11eb-81be-ae26e6f563ce.png)

**Comment by DarkDaniel107** [comment]
Had the same issue, but there was a power outage, so it may be well that the jar file corrupted.

**Comment by DarkDaniel107** [comment]
On second thought, it isn't. Redownloaded LiteXbantion and the same error appeared.

**Comment by J3fftw1** [comment]
wrong issue tracker

**Comment by J3fftw1** [comment]
https://github.com/Slimefun-Addon-Community/LiteXpansion
