### ISSUE TITLE
Capability addition for xpansion solar

### ISSUE THREAD

**Issue by mrcoffee1026** [J3fftw1/LiteXpansion#13]
Possibly make these operate in the nether and/or the end maybe with the use of an upgrade or even "as is", but possibly in the way that an Energized Solar panel also works without sunlight... just producing some amount less in the worlds without a sun, maybe not a LOT less since these are - as you say - end game machines and I have no idea of their normal output.

**Comment by J3fftw1** [comment]
like i said at it to #2
