### ISSUE TITLE
Solar panels reporting lag in new SF profiler

### ISSUE THREAD

**Issue by nagasiminecraft** [J3fftw1/LiteXpansion#22]
![image](https://user-images.githubusercontent.com/34377372/86481418-93207f00-bd82-11ea-852a-30e104d34bba.png)
![image](https://user-images.githubusercontent.com/34377372/86481445-9ca9e700-bd82-11ea-8fc1-6b452d462776.png)
Already using latest

**Comment by J3fftw1** [comment]
Show /sf versions please
Also show /timings not just these timings

**Comment by nagasiminecraft** [comment]
Timings: https://timings.aikar.co/?id=b0eab3ca75164ac1b1957db003464b04
![image](https://user-images.githubusercontent.com/34377372/86483351-7c7c2700-bd86-11ea-9e41-dc486b097498.png)
There

**Comment by WalshyDev** [comment]
Should be fixed in [build 41](https://thebusybiscuit.github.io/builds/J3fftw1/LiteXpansion/master#41)
