### ISSUE TITLE
Electric Chestplate not negating damage

### ISSUE THREAD

**Issue by OrangeCat555** [J3fftw1/LiteXpansion#26]
When someone is wearing the electric chestplate and takes damage this error occurs.

[https://pastebin.com/m7vAtAqy](url)

Versions: 
24.07 19:46:47 [Server] INFO Paper v1_16_R1
24.07 19:46:47 [Server] INFO CS-CoreLib vDEV - 90 (git 9dd4a1cf)
24.07 19:46:47 [Server] INFO Slimefun vDEV - 590 (git ee62a9b0)
24.07 19:46:47 [Server] INFO Installed Addons (5)
24.07 19:46:47 [Server] INFO Barrels vDEV - 12 (git 0f66f4c9)
24.07 19:46:47 [Server] INFO LiteXpansion vDEV - 47 (git ec034a10)
24.07 19:46:47 [Server] INFO SlimefunLuckyBlocks v2.7
24.07 19:46:47 [Server] INFO CMI v8.7.3.1
24.07 19:46:47 [Server] INFO ExoticGarden vDEV - 55 (git cce4c0f4)

**Comment by WalshyDev** [comment]
Fixed in build 55
