### ISSUE TITLE
Nanoblade and Electric Chestplate not working

### ISSUE THREAD

**Issue by Riley31415** [J3fftw1/LiteXpansion#28]
The nanoblade and electric chestplate seem to have stopped working in the latest build. I had first made a nano blade and upgraded to netherite and it didnt work, then made another one and enchanted it and it didnt work, then made a totally fresh one and it failed as well. The 2 that i didnt upgrade to netherite still lost energy when attacking, but didnt have the affect they are supposed to, they just acted like diamond swords. 
The electric chestplate was enchanted and then disenchanted, both ways it did not lose energy nor do what it was supposed to. 
I dont have access to any errors in console. I made sure the nano blade was turned on :) I tested it on different armors and people, and had them test it on me as well, none of which were successful.

**Comment by Riley31415** [comment]
After some testing, the issue only exists on 1.16 and it doesnt have anything to do with enchants from what i can tell. Something about 1.16 is messing it up.

**Comment by WalshyDev** [comment]
Fixed in build 55
