### ISSUE TITLE
Geo Scanner don`t work

### ISSUE THREAD

**Issue by Sashavovo** [J3fftw1/LiteXpansion#3]
GEO Resource "litexpansion:magthor" was misconfigured! getMaxDeviation() must return a value higher than zero!

**Comment by WalshyDev** [comment]
Fixed in opcoming build 16.

**Comment by TheBusyBiscuit** [comment]
Good I added this new error message :LuL:

**Comment by WalshyDev** [comment]
Any reason you won't allow deviation of 0 Cookie?
