### ISSUE TITLE
UU transmutator not chargeable

### ISSUE THREAD

**Issue by LoutreBleue** [J3fftw1/LiteXpansion#4]
## Description (Required)

The "UU transmutator is not chargeable, which means it doesn't get the energy it needs to function
## Steps to reproduce the Issue (Required)

Just try to use it
![image](https://user-images.githubusercontent.com/57031748/78698321-764ee980-7902-11ea-8754-5c665bfa2974.png)

## Expected behavior (Required)

That the block receive the energy it needs to function
## Server Log / Error Report

No error
## Environment (Required)

![image](https://user-images.githubusercontent.com/57031748/78698483-b615d100-7902-11ea-8001-bb07cb9cfe01.png)

**Comment by J3fftw1** [comment]
This is litexpansion not slimexpansion
Wrong issue tracker
