### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 100petr** [J3fftw1/LiteXpansion#45]
## Description (REQUIRED)

Error in console 

## Steps to reproduce the Issue (REQUIRED)

Start server

## Expected behavior (REQUIRED)

There will be no error in the console

## Server Log

error: https://pastebin.com/J666iKmU

## Environment (REQUIRED)

![nNcSD3CBSDmF5gvt4hcZ-A](https://user-images.githubusercontent.com/29830635/92106597-ee9fd500-ede4-11ea-994e-30e865e1074d.png)

**Comment by WalshyDev** [comment]
@J3fftw1 and this is why you don't just merge whenever

@NCBPFluffyBear your PR ^

You should check if SlimyTreeTaps is there and use that rubber instead of LX rubber. Also, LX rubber should have a different ID

**Comment by J3fftw1** [comment]
disable the lx item in the meanwhile till this is fixed
