### ISSUE TITLE
Players can control each other's Slimefun guides when in the UU matter category

### ISSUE THREAD

**Issue by NCBPFluffyBear** [J3fftw1/LiteXpansion#55]
## Description (REQUIRED)
When two players are in the LX UU Matter category, one player can click on recipes and control where the other player's menu leads.

## Steps to reproduce the Issue (REQUIRED)
1. Player 1 opens guide and navigates to UU Matter category
2. Player 2 opens guide and navigates to UU Matter category
3. Player 1 clicks an item (i.e. Lapis Lazuli)
4. Player 2's guide shows the UU matter recipe for lapis

## Expected behavior (REQUIRED)
the slimefun guides should not interfere with each other

## Server Log
No errors

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft version: 1.16.1
 - CS-CoreLib version: 90
 - Slimefun version: 665
 - LiteXpansion version: 66

Here's a video of me getting locked into the GUI :(
https://streamable.com/hz9haf

**Comment by J3fftw1** [comment]
fix in  #98
