### ISSUE TITLE
SCRAP_MACHINE disappears

### ISSUE THREAD

**Issue by siamneko** [J3fftw1/LiteXpansion#56]
## Description (REQUIRED)

Updated from Dev58 to Dev67 today
All SCRAP_MACHINE blocks disappeared in error
it disappears even if it is replaced

## Steps to reproduce the Issue (REQUIRED)

Install SCRAP_MACHINE

## Expected behavior (REQUIRED)

SCRAP_MACHINE must continue to exist

## Server Log

https://pastebin.com/ScDPgjKa
## Environment (REQUIRED)

 - Server Software (Spigot/Paper):Paper-185 
 - Minecraft version:1.16.2-R0.1-SNAPSHOT
 - CS-CoreLib version:90 (git 9dd4a1cf)
 - Slimefun version:665 (git 37576bb3)
 - LiteXpansion version:67 (git 7b2c9d05)

**Comment by WalshyDev** [comment]
Can you send the error file

**Comment by siamneko** [comment]
It is an error report of slimefun
https://pastebin.com/zz7xR0uP

**Comment by WalshyDev** [comment]
Fixed in build 68, will be available in like 15 mins.
