### ISSUE TITLE
Mass Fabricator & Scrap Machines dissapearing

### ISSUE THREAD

**Issue by lukemango** [J3fftw1/LiteXpansion#61]
## Description (REQUIRED)

Per request of your plugin, here's the error log provided:
https://pastebin.com/phXPuqDD
https://pastebin.com/phybb1sU

## Steps to reproduce the Issue (REQUIRED)

Contacted the player whose it was for response, will edit and add more information when they reply.
From the player:
"Yesterday I actually made 2 more mass fabricators because I was hoping at least to get one UU out of them (I made one before the restart and one after the restart). I made them, set them down where they would get power, put two stacks of scrap in them and a few seconds later they simply disappeared."

## Expected behavior (REQUIRED)

Blocks to not disspear randomly. (Afaik it's random, but will update with more information from the players that vanished)

## Server Log

Provided: https://pastebin.com/phybb1sU

## Environment (REQUIRED)

![](https://lukemango.com/O60jb.png)

**Comment by NCBPFluffyBear** [comment]
I used all these versions, but was unable to reproduce this. Did you happen to /reload the server? Is it possible that plugman tampered with Slimefun/LX?

**Comment by WalshyDev** [comment]
Update SF.
