### ISSUE TITLE
Scrap Machine Disappears

### ISSUE THREAD

**Issue by therbz** [J3fftw1/LiteXpansion#66]
## Description (REQUIRED)

When you put an item into a Scrap Machine and close the menu, the Scrap Machine disappears

## Steps to reproduce the Issue (REQUIRED)

Place a Scrap Machine
Put an item into the Scrap Machine
Close the menu

## Expected behavior (REQUIRED)

The Scrap Machine shouldn't disappear and shouldn't post an error to logs

## Server Log

Log: https://paste.gg/p/anonymous/3d25a978817644f18cd3d314352763cc
2020-09-14-18-42.err: https://paste.gg/p/anonymous/8d484e7182b441fd8373953b153c6b8d

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper-196
 - Minecraft version: 1.16.3
 - CS-CoreLib version: DEV 85
 - Slimefun version: DEV 633
 - LiteXpansion version: DEV 68

**Comment by WalshyDev** [comment]
40 builds behind. Update.
