### ISSUE TITLE
Hacktoberfest 2020

### ISSUE THREAD

**Issue by WalshyDev** [J3fftw1/LiteXpansion#78]
LiteXpansion is participating in the annual hacktoberfest this year. This is a cool oppotunity to contribute to open-source repostitories and get a **free limited edition t-shirt** or **plant a tree**!
You can sign up to Hacktoberfest [over here](https://hacktoberfest.digitalocean.com/)

## What qualifies as a hacktoberfest pull request?
* Documentation
* Bug fixes
* Implement suggestions (Please check the issues tab)
* Performance improvements

## What we don't want to see
* Pull Requests that break LiteXpansion
* If you fix a typo that is fine, but don't make 5 PRs each fixing a single typo
* Code style changes
* Breaking changes

## Suggested PRs
* Update the [README](https://github.com/J3fftw1/LiteXpansion/blob/master/README.md)
* Fixing some [Bugs](https://github.com/J3fftw1/LiteXpansion/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug)
* Fixing typos
* Performance improvements

If your change is one of the listed cases then please use the opportunity of this event for your pull request. We recommend commenting on this issue if you start working on a change in order to avoid multiple users working on the same thing.

Happy contributing from the LiteXpansion team!

**Comment by IAmSorryArt** [comment]
@WalshyDev @J3fftw1 Can I do the README for you? :D

**Comment by J3fftw1** [comment]
Yea, ofcourse i wanted to remove it and make a more static 1 my self but if you are up for it thats cool
But the items and such i want them moved to the wiki
