### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by J3fftw1** [J3fftw1/LiteXpansion#81]
Make items, messages, lore, etc etc translatable.
Right now we are in a pretty early stage of the plugin that it would be do able.

**Comment by charchitmangal** [comment]
hello! I am interested in this, please assign me!

**Comment by J3fftw1** [comment]
I look forward for your pr. And thanks for wanting to contribute

**Comment by J3fftw1** [comment]
if you need any help or have any questions you can leave them here or message me on discord Panda.com#0806 or join the discord server https://discord.gg/slimefun

**Comment by J3fftw1** [comment]
This issue is still open and not taken
