### ISSUE TITLE
[Suggestion] Is it possible to depend my addon on this one? If not, please make it possible!

### ISSUE THREAD

**Issue by developer-pseudo** [J3fftw1/LiteXpansion#93]
I would like my addon to depend on liteXpansion, so I can use some built in stuff I don't want to code.

**Comment by J3fftw1** [comment]
Thats possible just add it like a dependency just like you add every other plugin

**Comment by developer-pseudo** [comment]
Alright, thanks.

**Comment by J3fftw1** [comment]
Mind sending a link to the repo when you have started working on it.

**Comment by developer-pseudo** [comment]
Yeha.

**Comment by J3fftw1** [comment]
closing this issue feel free to mention me on discord with the link or post it in the closed issue i will get the notification when posted
my discord is Panda.com#0806. you could also join the slimefun server and mention me there https://discord.gg/slimefun
